#include "rcc.h"

void RCC_voidEnableGPIOA(void)
{
    SET_BIT(RCC_REG(RCC_AHB1ENR_OFFSET), RCC_AHB1ENR_GPIOAEN_BIT);
}

void RCC_voidEnableGPIOB(void)
{
    SET_BIT(RCC_REG(RCC_AHB1ENR_OFFSET), RCC_AHB1ENR_GPIOBEN_BIT);
}

void RCC_voidEnableDMA2(void)
{
    SET_BIT(RCC_REG(RCC_AHB1ENR_OFFSET), RCC_AHB1ENR_DMA2EN_BIT);
}

void RCC_voidEnableTIM3(void)
{
    SET_BIT(RCC_REG(RCC_APB1ENR_OFFSET), RCC_APB1ENR_TIM3EN_BIT);
}

void RCC_voidEnableADC1(void)
{
    SET_BIT(RCC_REG(RCC_APB2ENR_OFFSET), RCC_APB2ENR_ADC1EN_BIT);
}
